<a href="https://colab.research.google.com/github/ann-nikki/first_repository/blob/main/Untitled26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def message(input_text): #название ф-ции
    return f"Уважаемый, {input_text}!Вы верно выполнили это задание!"

In [ ]:
#Напишите функцию summa_n, которая принимает одно целое положительное число t и находит сумму всех чисел от 1 до t включительно.
#Вызывать в скрипте функцию не нужно.
def summa_n(t):
    t = (int(input("Введите число: ")))
    l1 = [t]
    for i in range(1,t): #сама ф-ция
        l1.append(i)
    S = sum(l1)
    return f"Я знаю, что сумма чисел от 1 до {t} равна {S}"

In [ ]:
def summa_n(t):
    S = 0
    for i in range(1,t+1): #сама ф-ция
      S += 1
    return f"Я знаю, что сумма чисел от 1 до {t} равна {S}"

In [ ]:
#Практическое задание 4.3
#Объявите функцию square_number(), которая принимает один аргумент (вещественное число)(float) , и возвращает квадрат этого числа.
#Вызывать в скрипте функцию не нужно.
def square_number(n):
    return n**2

In [ ]:
#Практическое задание 4.4
def is_long(s1):
    retun len(s1) = 10 #true <class 'bool'>

In [ ]:
#Практическое задание 4.5
def analyze_prices(l):
    l = list(map(int, l.split()))
    return f'Min = {min(l)}, max = {max(l)}, sum = {sum(l)}'

In [ ]:
a, b = map(int, input().split(', '))
l = []
for i in range(1, b):
    if a < (i** 2) < b:
        l.append(str(i))
print(', '.join(l))

50, 100
8, 9

In [ ]:
import sqrt from math

print(sqrt(9))

SyntaxError: invalid syntax (<ipython-input-5-a3d145ce2982>, line 1)

Напишите функцию random_character() для вывода случайного символа из заданной строки

Файл с решением должен иметь название task5_1.py, название функции - def random_character(). Вызывать в скрипте функцию не нужно

Пример ввода:
world

Вывод:

r

In [ ]:
import random
def random_character(stdin):
    return random.choice(stdin)

In [ ]:
import random
def random_character(stdin):
    return stdin[random.randint(0, len(stdin)-1)]

In [ ]:
#Практическое задание 4.4
def is_long(s1):
    retun len(s1) = 10 #true <class 'bool'>

Напишите функцию area_and_length(), определяющую площадь круга и длину окружности, по заданному радиусу R. Используйте модуль math

! Результат округлите до сотых

Вывод результата в виде строки (без кавычек):

"Circle area = circle_area, circle length = circle_length"
Файл с решением должен иметь название task5_2.py, название функции - def area_and_length(). Вызывать в скрипте функцию не нужно.

Тестовый пример:

area_and_length(23)

Вывод:
Circle area = 1661.9, circle length = 144.51

In [ ]:
import math
def area_and_length(stdin):
    stdin = float()
    from math import pi
    circle_area = pi*pow(stdin,2)
    circle_area = round(circle_area,2)
    circle_lenght = pi*(stdin*2)
    circle_lenght = round(circle_lenght, 2)
    return f'Circle area = {circle_area}, circle length = {circle_lenght}'

In [ ]:
import math
def area_and_length(stdin):
    return f'Circle area = {round((math.pi*float(stdin)*float(stdin)), 2)}, circle length = {round((2*math.pi*float(stdin)),2)}'

In [ ]:
import pandas as pd
def row_col_num(file):
    data = pd.read_csv(file)
    row = data.shape[0]
    cols = data.shape[1]
    return (f"В таблице {row} строки и {cols} столбцов")

In [ ]:
def read_file_last(data,n):
  file = open(data, "r+")
  str_list = file.readlines()
  new_list = [i.replace("\n,"") for i in str_list]
  file.close()
  return new_list[-n:]

In [ ]:
# 6.3 Работа с предустановленными файлами в Google Colab
import pandas as pd # импортируем библиотеку pandas
#  метод read_csv() для работы с csv-файлами. Обычно в файлах этого типа хранятся данные для анализа
 #(с файлами других расширений тоже можно работать, для это используются другие методы, например – read_json() или read_html()).
data = pd.read_csv('/content/sample_data/california_housing_train.csv') #вставляем путь файла, чтобы записать его в переменную
data.head() #В переменной data лежат наши данные в виде таблицы - датафрейма.
#Можем вывести первые 5 строк таблицы методом head() (в скобках можно указывать количество выводимых строк, по умолчанию выводит 5):

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

Чтобы извлечь данные из файла, нам нужно:

1)       Загрузить файл во временное хранилище Google Colab;

2)       Указать верный путь.

In [ ]:
data_2 = pd.read_csv('/content/titanic.csv') #вставляем путь файла про титаник
data_2.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
data_3 = pd.read_csv('/content/drive/MyDrive/Files for Colab/titanic.csv') #загружаю файл со своего гугл диска
data_2.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S